name: estore
description: A new Ept1 project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter  
 
  image_picker: ^1.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  image: ^4.0.17
  math_expressions: ^2.0.0 


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: 



flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/brand/
